FROM ubuntu:latest

RUN apt update && apt install -y \
                      python3 \
                      strace \
                      nano \
                      net-tools \
                      netcat \
                      curl \
                      ssh-client

RUN mkdir -m 0700 /p2p/

COPY ./app/0-node/inputthread.py /p2p/inputthread.py
COPY ./app/0-node/inputcallback.py /p2p/inputcallback.py
COPY ./app/0-node/node_fnc.py /p2p/node_fnc.py
COPY ./app/0-node/init.py /p2p/init.py
COPY ./app/0-node/node.py /p2p/node.py

RUN chmod 0700 \
    /p2p/inputthread.py \
    /p2p/init.py \
    /p2p/inputcallback.py \
    /p2p/node_fnc.py \
    /p2p/init.py

ENTRYPOINT ["python3", "/p2p/init.py"]