FROM python:3.10.5-alpine

RUN apk update && apk add --no-cache \
                          strace \
                          nano \
                          net-tools \
                          curl \
                          openssh-client \
                          proxychains-ng
                      
RUN mkdir -m 0700 /p2p/

COPY ./app/def-node/inputthread.py /p2p/inputthread.py
COPY ./app/def-node/inputcallback.py /p2p/inputcallback.py
COPY ./app/def-node/node_fnc.py /p2p/node_fnc.py
COPY ./app/def-node/init.py /p2p/init.py
COPY ./app/def-node/node.py /p2p/node.py

RUN chmod 0700 \
    /p2p/inputthread.py \
    /p2p/init.py \
    /p2p/inputcallback.py \
    /p2p/node_fnc.py \
    /p2p/init.py

COPY ./deployment/def-node-entrypoint.sh /node-entrypoint.sh
RUN chmod 0700 /node-entrypoint.sh

# ENTRYPOINT ["python3", "/p2p/init.py", "45666", "p2p-0-node-connector:45555"]