FROM python:3.10.5-alpine

RUN apk update && apk add --no-cache \
                          strace \
                          nano \
                          net-tools \
                          curl \
                          openssh-client \
                          nmap \
                          proxychains-ng

RUN mkdir -m 0700 /p2p/

COPY ./app/0-node/inputthread.py /p2p/inputthread.py
COPY ./app/0-node/inputcallback.py /p2p/inputcallback.py
COPY ./app/0-node/node_fnc.py /p2p/node_fnc.py
COPY ./app/0-node/tcp_http_headers.py /p2p/tcp_http_headers.py
COPY ./app/0-node/init.py /p2p/init.py
COPY ./app/0-node/node.py /p2p/node.py

RUN chmod 0700 \
    /p2p/inputthread.py \
    /p2p/init.py \
    /p2p/inputcallback.py \
    /p2p/node_fnc.py \
    /p2p/init.py

RUN touch /p2p/ips.txt && \
    chmod 0666 /p2p/ips.txt

COPY ./deployment/0-node-entrypoint.sh /node-entrypoint.sh
RUN chmod 0700 /node-entrypoint.sh

# ENTRYPOINT ["python3", "/p2p/init.py"]