FROM python:3.10.5-alpine

RUN apk update && apk add --no-cache \
                          strace \
                          nano \
                          net-tools \
                          curl \
                          openssh-client \
                          nmap \
                          proxychains-ng

RUN mkdir -m 0700 /p2p/ && \
    mkdir -p /p2p/cstmcrypt/RSA-keys && \
    mkdir -p /p2p/cstmcrypt/AES-keys

COPY ./deployment/src/0-node /p2p/

RUN touch /p2p/ips.txt && \
    chmod 0700 /p2p/init.py && \
    chmod 0666 /p2p/ips.txt

COPY ./deployment/0-node-entrypoint.sh /node-entrypoint.sh
RUN chmod 0700 /node-entrypoint.sh

# ENTRYPOINT ["python3", "/p2p/init.py"]