# apiVersion: v1
# kind: Namespace
# metadata:
#   name: {{ .Values.namespace }}
#   labels:
#     app.kubernetes.io/managed-by: "Helm"
#   annotations:
#     meta.helm.sh/release-name: "p2p-net"
#     meta.helm.sh/release-namespace: "p2p"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.defNodeName }}
  labels:
    app: {{ .Values.defNodeApp }}
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "p2p-net"
    meta.helm.sh/release-namespace: "p2p"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.defNodeApp }}
  template:
    metadata:
      labels:
        app: {{ .Values.defNodeApp }}
    spec:
      containers:
      - name: {{ .Values.defNodeApp }}
        image: {{ .Values.defNodeImage }}
        tty: true
        stdin: true
        ports:
        - containerPort: {{ .Values.defNodeContainerPort }}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 50m
            memory: 200Mi
          requests:
            cpu: 20m
            memory: 100Mi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.botNodeName }}
  labels:
    app: {{ .Values.botNodeApp }}
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "p2p-net"
    meta.helm.sh/release-namespace: "p2p"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.botNodeApp }}
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: {{ .Values.botNodeApp }}
    spec:
      containers:
      - name: {{ .Values.botNodeApp }}
        image: {{ .Values.botNodeImage }}
        tty: true
        ports:
        - containerPort: {{ .Values.botNodeContainerPort }}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 50m
            memory: 200Mi
          requests:
            cpu: 20m
            memory: 100Mi


---
apiVersion: v1
kind: Pod
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.node0Name }}
  labels:
    app: {{ .Values.node0App }}
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "p2p-net"
    meta.helm.sh/release-namespace: "p2p"
spec:
  containers:
  - name: node-0
    image: {{ .Values.node0Image }}
    tty: true
    stdin: true
    ports:
    - containerPort: {{ .Values.node0ContainerPort }}
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 50m
        memory: 200Mi
      requests:
        cpu: 20m
        memory: 100Mi


---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.node0ServiceName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "p2p-net"
    meta.helm.sh/release-namespace: "p2p"
spec:
  clusterIP: None
  # type: NodePort
  selector:
    app: {{ .Values.node0Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.node0ServicePort }}
      targetPort: {{ .Values.node0ContainerPort }}

---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.defNodeServiceName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "p2p-net"
    meta.helm.sh/release-namespace: "p2p"
spec:
  clusterIP: None
  # type: NodePort
  selector:
    app: {{ .Values.defNodeApp }}
  ports:
    - protocol: TCP
      port: {{ .Values.defNodeContainerPort }}
      targetPort: {{ .Values.defNodeServicePort }}


---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.botNodeServiceName }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "p2p-net"
    meta.helm.sh/release-namespace: "p2p"
spec:
  clusterIP: None
  # type: NodePort
  selector:
    app: {{ .Values.botNodeApp }}
  ports:
    - protocol: TCP
      port: {{ .Values.botNodeContainerPort }}
      targetPort: {{ .Values.botNodeServicePort }}
