---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: {{ .Values.node0App }}
  namespace: {{ .Values.namespace }}
  name: {{ .Values.node0Name }}
spec:
  containers:
  - name: node-0
    image: {{ .Values.node0Image }}
    tty: true
    stdin: true
    ports:
    - containerPort: {{ .Values.node0ContainerPort }}
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 50m
        memory: 200Mi
      requests:
        cpu: 20m
        memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.node0ServiceName }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.node0Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.node0ServicePort }}
      targetPort: {{ .Values.node0ContainerPort }}