###################
# BOT NODE
###################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.botNodeApp }}
  labels:
    app: {{ .Values.botNodeApp }}
    app.kubernetes.io/managed-by: {{ .Values.labelManagedBy }}
  annotations:
    meta.helm.sh/release-name: {{ .Values.annotationReleaseName }}
    meta.helm.sh/release-namespace: {{ .Values.annotationReleaseNamespace }}
spec:
  replicas: {{ .Values.botNodeReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.botNodeApp }}
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: {{ .Values.botNodeApp }}
    spec:
      containers:
      - name: {{ .Values.botNodeApp }}
        image: {{ .Values.botNodeImage }}
        command: ["/bin/sh"]
        args: ["-c", "/node-entrypoint.sh"]
        stdin: {{ .Values.stdin }}
        tty: {{ .Values.tty }}
        ports:
        - containerPort: {{ .Values.botNodeContainerPort }}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: {{ .Values.limitsCpu }}
            memory: {{ .Values.limitsMemory }}
          requests:
            cpu: {{ .Values.requestsCpu }}
            memory: {{ .Values.requestsMemory }}

###################
# 0 NODE
###################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.node0App }}
  labels:
    app: {{ .Values.node0App }}
    app.kubernetes.io/managed-by: {{ .Values.labelManagedBy }}
  annotations:
    meta.helm.sh/release-name: {{ .Values.annotationReleaseName }}
    meta.helm.sh/release-namespace: {{ .Values.annotationReleaseNamespace }}
spec:
  replicas: {{ .Values.node0Replicas }}
  selector:
    matchLabels:
      app: {{ .Values.node0App }}
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: {{ .Values.node0App }}
    spec:
      containers:
      - name: {{ .Values.node0App }}
        image: {{ .Values.node0Image }}
        command: ["/bin/sh"]
        args: ["-c", "/node-entrypoint.sh"]
        stdin: {{ .Values.stdin }}
        tty: {{ .Values.tty }}
        ports:
        - containerPort: {{ .Values.node0ContainerPort }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
          limits:
            cpu: {{ .Values.limitsCpu }}
            memory: {{ .Values.limitsMemory }}
          requests:
            cpu: {{ .Values.requestsCpu }}
            memory: {{ .Values.requestsMemory }}


#########################################################################

################### BOT NODE
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.botNodeServiceName }}
  labels:
    app.kubernetes.io/managed-by: {{ .Values.labelManagedBy }}
  annotations:
    meta.helm.sh/release-name: {{ .Values.annotationReleaseName }}
    meta.helm.sh/release-namespace: {{ .Values.annotationReleaseNamespace }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Values.botNodeApp }}
  ports:
    - protocol: {{ .Values.serviceProtocol }}
      port: {{ .Values.botNodeContainerPort }}
      targetPort: {{ .Values.botNodeServicePort }}
      nodePort: {{ .Values.botNodePort }}

################### NODE 0
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.node0ServiceName }}
  labels:
    app.kubernetes.io/managed-by: {{ .Values.labelManagedBy }}
  annotations:
    meta.helm.sh/release-name: {{ .Values.annotationReleaseName }}
    meta.helm.sh/release-namespace: {{ .Values.annotationReleaseNamespace }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Values.node0App }}
  ports:
    - protocol: {{ .Values.serviceProtocol }}
      port: {{ .Values.node0ServicePort }}
      targetPort: {{ .Values.node0ContainerPort }}
      nodePort: {{ .Values.node0NodePort }}

###################################### 
# TEST POD                           #
# ####################################
---
apiVersion: v1
kind: Pod
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.testnodePod }}
  labels:
    app: {{ .Values.node0App }}
    app.kubernetes.io/managed-by: {{ .Values.labelManagedBy }}
  annotations:
    meta.helm.sh/release-name: {{ .Values.annotationReleaseName }}
    meta.helm.sh/release-namespace: {{ .Values.annotationReleaseNamespace }}
spec:
  containers:
  - name: {{ .Values.testnodePod }}
    image: {{ .Values.node0Image }}
    stdin: {{ .Values.stdin }}
    tty: {{ .Values.tty }}
    ports:
    - containerPort: {{ .Values.testnodePodPort1 }}
    - containerPort: {{ .Values.testnodePodPort2 }}
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: {{ .Values.limitsCpu }}
        memory: {{ .Values.limitsMemory }}
      requests:
        cpu: {{ .Values.requestsCpu }}
        memory: {{ .Values.requestsMemory }}
